services:
  backend:
    volumes:
      - ./runtime/pre/uploads:/app/src/uploads
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/escapefinder_pre
      REDIS_URL: redis://cache:6379/1
